/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fish_calnum_Compute */

#ifndef _Included_com_fish_calnum_Compute
#define _Included_com_fish_calnum_Compute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fish_calnum_Compute
 * Method:    add
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_fish_calnum_Compute_add
  (JNIEnv *, jclass, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
